#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'RequestMessage'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 0

# The Active Message type associated with this message.
AM_TYPE = -1

class RequestMessage(tinyos.message.Message.Message):
    # Create a new RequestMessage of size 0.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=0):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <RequestMessage> \n"
        return s

    # Message-type-specific access methods appear below.

